### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [2]:
import numpy as np

#1-
def is_primo(x):
    vet = list(range(2, int(np.sqrt(x)) +1 ))
    for i in vet:
        if x % i == 0:
            return 0
    return 1

vet_1 = [i for i in list(range(0,21)) if is_primo(i) and i > 1]
vet_1 = np.array(vet_1)
vet_1
       

array([ 2,  3,  5,  7, 11, 13, 17, 19])

In [11]:

#2-
[i for i in vet_1 if i > 10]
vet_1 > 10

 

array([False, False, False, False,  True,  True,  True,  True])

In [12]:

#3-
vet_1 %2 == 0 
        

array([ True, False, False, False, False, False, False, False])

### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [13]:
a = np.array([range(1,5), range(5,9), range(9,13), range(13,17)])
a, a.ndim



(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 2)

In [15]:
b = a[[1, 3]]
b


array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [17]:

c = a[2]
c




array([ 9, 10, 11, 12])

In [18]:
a / c 

array([[0.11111111, 0.2       , 0.27272727, 0.33333333],
       [0.55555556, 0.6       , 0.63636364, 0.66666667],
       [1.        , 1.        , 1.        , 1.        ],
       [1.44444444, 1.4       , 1.36363636, 1.33333333]])

### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [104]:
arr = np.random.rand(10,3)
arr

array([[0.80996191, 0.2439503 , 0.61540561],
       [0.08197235, 0.91923723, 0.10618794],
       [0.74891046, 0.64550598, 0.62874472],
       [0.02334996, 0.9812276 , 0.35734763],
       [0.16497339, 0.28197002, 0.34511716],
       [0.19036028, 0.39189049, 0.43812249],
       [0.24492124, 0.88542484, 0.38210216],
       [0.57177699, 0.99886779, 0.72816071],
       [0.55266283, 0.12695508, 0.35555796],
       [0.83742516, 0.33274647, 0.14980868]])

In [105]:

x = 0.5
dist = np.abs(arr - x)
indice = np.argmin(dist, axis=1 )
row = list(range(10))
arr[row,indice]


array([0.61540561, 0.10618794, 0.62874472, 0.35734763, 0.34511716,
       0.43812249, 0.38210216, 0.57177699, 0.55266283, 0.33274647])

### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [107]:
#1-
array = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
array


array([ 68,  65,  77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164,
       163, 162, 100,  90,  97,  72,  60,  70])

In [110]:

#2-
fre_min = np.min(array)
print("la frequenza minima è:",fre_min.item())
#array[array.argmin()].item()


la frequenza minima è: 60


In [111]:

#3-

fre_max = np.max(array)
print("la frequenza massima è:",fre_max.item())
#array[array.argmax()].item()


la frequenza massima è: 164


In [112]:

#4-
    #a-
array_2 = array > 120
array_2


array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False])

In [115]:

    #b-
percentuale = np.sum(array_2) / np.sum(array)
percentuale.item() *100
print("il percentuale è : {} %".format(round(percentuale.item() *100, 2)) )


il percentuale è : 0.43 %


### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [117]:
#1-
vettore = np.array( [50000, 105250, 55000, 89000])
cost_tot = np.sum(vettore).item()
cost_tot

299250

In [118]:

#2-
vettore[vettore== 105250 ]  = vettore[vettore== 105250 ] + (vettore[vettore== 105250 ] * 15) / 100
vettore


array([ 50000, 121037,  55000,  89000])

In [119]:

#3- 
print("Si, capisco, perché gli elementi dell'array di base erano del tipo 'int'")


Si, capisco, perché gli elementi dell'array di base erano del tipo 'int'


In [120]:

#4-
vettore_flot = np.array( [50000.0, 105250, 55000, 89000])
vettore_flot[vettore_flot == 105250 ]  = vettore_flot [vettore_flot == 105250 ] + (vettore_flot [vettore_flot == 105250 ] * 15) / 100
vettore_flot, vettore_flot.dtype


(array([ 50000. , 121037.5,  55000. ,  89000. ]), dtype('float64'))

In [121]:

#5-
vettore_flot[vettore_flot == 50000.0] = vettore_flot[vettore_flot == 50000.0] + (vettore_flot[vettore_flot == 50000.0]*20) / 100
vettore_flot



array([ 60000. , 121037.5,  55000. ,  89000. ])

In [122]:

#6-
vettore_flot[vettore_flot == 55000.0] = vettore_flot[vettore_flot == 55000.0] + (vettore_flot[vettore_flot == 55000.0]*10) /100
vettore_flot[vettore_flot == 89000.0] = vettore_flot[vettore_flot == 89000.0] + (vettore_flot[vettore_flot == 89000.0]*10) /100
vettore_flot


array([ 60000. , 121037.5,  60500. ,  97900. ])

In [123]:

#7-
aumento = np.sum(vettore_flot)

spese_totali = aumento - cost_tot
spese_totali.item()




40187.5

### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

In [128]:
#1-
## Generazione di 200 valori casuali di emissioni di CO2 in tonnellate per anno 
## Supponiamo emissioni tra 4 e 20 tonnellate per persona 
np.random.seed(123)
co2_emissions = np.round(np.random.uniform(4, 20, 200), 2)

## Nome del file di output
output_file = "C:\\Users\\delma\\OneDrive\\Bureau\\my_project_pytho_II\\co2.txt"

## Salvataggio su file
np.savetxt(output_file, co2_emissions, fmt="%.2f")

## Restituisco il percorso del file
output_file


'C:\\Users\\delma\\OneDrive\\Bureau\\my_project_pytho_II\\co2.txt'

In [129]:

#2-
df = np.loadtxt(output_file)
df
sopra_ton = df[df > 18 ]
lenght = len(sopra_ton)
media = round(np.mean(sopra_ton).item(), 3)
lenght, media
print("ci sono {} valori e la loro media è {}".format(lenght, media))

ci sono 18 valori e la loro media è 18.963


In [133]:

#3-
som_soglia = round(np.sum(df[df > 18]).item(), 4)
som_soglia
sum_tot = np.sum(df)
sum_tot.item()
result = som_soglia / sum_tot
print("la frazione totale di emissione sopra la soglia è: {}".format(round(result,3)))

la frazione totale di emissione sopra la soglia è: 0.142


### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [143]:
# %%timeit
survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])

#1-
survey_matrix.ndim
select = survey_matrix[survey_matrix[:,2 ] >= 12]
select


array([[   32, 52000,    12],
       [   40, 63000,    14],
       [   35, 58000,    13]])

In [141]:

#2-
red = [i.item() for i in select[:,1] if i ]
red


[52000, 63000, 58000]

In [144]:

#3-
media = round(np.mean(select[:,1]).item(), 3)
print("la media è:", media)


la media è: 57666.667


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [154]:
import numpy as np
import matplotlib.pylab as plt
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

#plt.boxplot(ages)
#plt.title("Détection des outliers")
#plt.show()
IQR = np.percentile(ages, 75)  -  np.percentile(ages, 25)
IQR.item()
born_inf =  np.percentile(ages, 25) - 1.5*IQR
born_sup =  np.percentile(ages, 75) + 1.5*IQR
# born_inf.item(), born_sup.item()
# outliers = ages[(ages < born_inf) | (ages > born_sup)]
# outliers = np.median(ages)
# outliers
ages[ages > born_sup] = np.median(ages)
ages[ages < born_inf] = np.median(ages)
ages




array([ 92, 108,  75,  63,  62,  66,  90,  98,  97,  92,  60, 107,  90,
        71,  97,  86,  55,  55,  98,  57,  96, 104,  96,  94,  72,  98,
       111,  98,  89,  69,  77,  92,  85, 101,  93, 100,  90, 101,  96,
        98,  83,  87, 106,  86, 108,  55,  67,  65,  68,  59,  67,  72,
        57,  79,  95,  67,  86,  70,  91, 111,  67,  75,  59,  88,  90,
        99,  94,  65, 111, 103, 100,  70,  63,  65, 100, 110,  83,  70,
        57,  75,  56, 104, 111,  90,  74, 100,  90,  86,  88,  99,  58,
       103,  88, 103,  64,  96, 105,  89,  83,  65, 100,  62,  73, 105,
        83, 105,  58,  96,  77,  74,  95, 109,  91, 101,  91,  83,  63,
       111,  97, 108,  75,  77,  73,  58,  94,  83,  90,  61, 110, 107,
       105,  85,  64,  66,  71, 107, 105,  72,  78,  66, 100, 102,  72,
        83,  74,  68,  73,  72,  90,  93,  99,  55,  92,  83,  58,  71,
        89,  75,  98,  87,  83,  78,  97,  71, 106,  83,  58,  81, 100,
        72,  93,  70,  65,  60,  95, 107,  94,  77,  87,  90,  8

In [153]:
anciano = np.max(ages).item()
print("il piu anziano ha {} anni:".format(anciano ))

il piu anziano ha 112 anni:


### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il FILOSOFIA come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "VERDURA".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un SERBATOIO.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza IMPERO!" Ci fu grande gioia e celebrazione."*


In [202]:
import random
random.seed(123)
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]
random.sample(lista_parole, 5)


['APPLICAZIONE', 'FILOSOFIA', 'VERDURA', 'SERBATOIO', 'IMPERO']

Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."